// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wallet.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unspent struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 int32    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	ScriptPubKey         string   `protobuf:"bytes,5,opt,name=scriptPubKey,proto3" json:"scriptPubKey,omitempty"`
	Amount               float32  `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unspent) Reset()         { *m = Unspent{} }
func (m *Unspent) String() string { return proto.CompactTextString(m) }
func (*Unspent) ProtoMessage()    {}
func (*Unspent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{0}
}

func (m *Unspent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unspent.Unmarshal(m, b)
}
func (m *Unspent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unspent.Marshal(b, m, deterministic)
}
func (m *Unspent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unspent.Merge(m, src)
}
func (m *Unspent) XXX_Size() int {
	return xxx_messageInfo_Unspent.Size(m)
}
func (m *Unspent) XXX_DiscardUnknown() {
	xxx_messageInfo_Unspent.DiscardUnknown(m)
}

var xxx_messageInfo_Unspent proto.InternalMessageInfo

func (m *Unspent) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Unspent) GetVout() int32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *Unspent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Unspent) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Unspent) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

func (m *Unspent) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type InsertAddressRequest struct {
	Cointype             string   `protobuf:"bytes,1,opt,name=cointype,proto3" json:"cointype,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Privk                string   `protobuf:"bytes,3,opt,name=privk,proto3" json:"privk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAddressRequest) Reset()         { *m = InsertAddressRequest{} }
func (m *InsertAddressRequest) String() string { return proto.CompactTextString(m) }
func (*InsertAddressRequest) ProtoMessage()    {}
func (*InsertAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{1}
}

func (m *InsertAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAddressRequest.Unmarshal(m, b)
}
func (m *InsertAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAddressRequest.Marshal(b, m, deterministic)
}
func (m *InsertAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAddressRequest.Merge(m, src)
}
func (m *InsertAddressRequest) XXX_Size() int {
	return xxx_messageInfo_InsertAddressRequest.Size(m)
}
func (m *InsertAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAddressRequest proto.InternalMessageInfo

func (m *InsertAddressRequest) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

func (m *InsertAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertAddressRequest) GetPrivk() string {
	if m != nil {
		return m.Privk
	}
	return ""
}

type InsertAddressResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Success              string   `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAddressResponse) Reset()         { *m = InsertAddressResponse{} }
func (m *InsertAddressResponse) String() string { return proto.CompactTextString(m) }
func (*InsertAddressResponse) ProtoMessage()    {}
func (*InsertAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{2}
}

func (m *InsertAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAddressResponse.Unmarshal(m, b)
}
func (m *InsertAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAddressResponse.Marshal(b, m, deterministic)
}
func (m *InsertAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAddressResponse.Merge(m, src)
}
func (m *InsertAddressResponse) XXX_Size() int {
	return xxx_messageInfo_InsertAddressResponse.Size(m)
}
func (m *InsertAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAddressResponse proto.InternalMessageInfo

func (m *InsertAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertAddressResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type GetHDAddressRequest struct {
	Cointype             string   `protobuf:"bytes,1,opt,name=cointype,proto3" json:"cointype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHDAddressRequest) Reset()         { *m = GetHDAddressRequest{} }
func (m *GetHDAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetHDAddressRequest) ProtoMessage()    {}
func (*GetHDAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{3}
}

func (m *GetHDAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHDAddressRequest.Unmarshal(m, b)
}
func (m *GetHDAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHDAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetHDAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHDAddressRequest.Merge(m, src)
}
func (m *GetHDAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetHDAddressRequest.Size(m)
}
func (m *GetHDAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHDAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHDAddressRequest proto.InternalMessageInfo

func (m *GetHDAddressRequest) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

type GetHDAddressResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHDAddressResponse) Reset()         { *m = GetHDAddressResponse{} }
func (m *GetHDAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetHDAddressResponse) ProtoMessage()    {}
func (*GetHDAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{4}
}

func (m *GetHDAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHDAddressResponse.Unmarshal(m, b)
}
func (m *GetHDAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHDAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetHDAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHDAddressResponse.Merge(m, src)
}
func (m *GetHDAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetHDAddressResponse.Size(m)
}
func (m *GetHDAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHDAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHDAddressResponse proto.InternalMessageInfo

func (m *GetHDAddressResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SignEthTransRequest struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Nonce                string   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Gaslimit             string   `protobuf:"bytes,6,opt,name=gaslimit,proto3" json:"gaslimit,omitempty"`
	Gasprice             string   `protobuf:"bytes,7,opt,name=gasprice,proto3" json:"gasprice,omitempty"`
	Chainid              string   `protobuf:"bytes,8,opt,name=chainid,proto3" json:"chainid,omitempty"`
	Contract             string   `protobuf:"bytes,9,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignEthTransRequest) Reset()         { *m = SignEthTransRequest{} }
func (m *SignEthTransRequest) String() string { return proto.CompactTextString(m) }
func (*SignEthTransRequest) ProtoMessage()    {}
func (*SignEthTransRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{5}
}

func (m *SignEthTransRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignEthTransRequest.Unmarshal(m, b)
}
func (m *SignEthTransRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignEthTransRequest.Marshal(b, m, deterministic)
}
func (m *SignEthTransRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignEthTransRequest.Merge(m, src)
}
func (m *SignEthTransRequest) XXX_Size() int {
	return xxx_messageInfo_SignEthTransRequest.Size(m)
}
func (m *SignEthTransRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignEthTransRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignEthTransRequest proto.InternalMessageInfo

func (m *SignEthTransRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignEthTransRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SignEthTransRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SignEthTransRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *SignEthTransRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SignEthTransRequest) GetGaslimit() string {
	if m != nil {
		return m.Gaslimit
	}
	return ""
}

func (m *SignEthTransRequest) GetGasprice() string {
	if m != nil {
		return m.Gasprice
	}
	return ""
}

func (m *SignEthTransRequest) GetChainid() string {
	if m != nil {
		return m.Chainid
	}
	return ""
}

func (m *SignEthTransRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type SignEthTransResponse struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Rawhash              string   `protobuf:"bytes,2,opt,name=rawhash,proto3" json:"rawhash,omitempty"`
	Success              string   `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignEthTransResponse) Reset()         { *m = SignEthTransResponse{} }
func (m *SignEthTransResponse) String() string { return proto.CompactTextString(m) }
func (*SignEthTransResponse) ProtoMessage()    {}
func (*SignEthTransResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{6}
}

func (m *SignEthTransResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignEthTransResponse.Unmarshal(m, b)
}
func (m *SignEthTransResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignEthTransResponse.Marshal(b, m, deterministic)
}
func (m *SignEthTransResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignEthTransResponse.Merge(m, src)
}
func (m *SignEthTransResponse) XXX_Size() int {
	return xxx_messageInfo_SignEthTransResponse.Size(m)
}
func (m *SignEthTransResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignEthTransResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignEthTransResponse proto.InternalMessageInfo

func (m *SignEthTransResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignEthTransResponse) GetRawhash() string {
	if m != nil {
		return m.Rawhash
	}
	return ""
}

func (m *SignEthTransResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type SignBtcTransRequest struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Unspentlist          []byte   `protobuf:"bytes,5,opt,name=unspentlist,proto3" json:"unspentlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignBtcTransRequest) Reset()         { *m = SignBtcTransRequest{} }
func (m *SignBtcTransRequest) String() string { return proto.CompactTextString(m) }
func (*SignBtcTransRequest) ProtoMessage()    {}
func (*SignBtcTransRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{7}
}

func (m *SignBtcTransRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignBtcTransRequest.Unmarshal(m, b)
}
func (m *SignBtcTransRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignBtcTransRequest.Marshal(b, m, deterministic)
}
func (m *SignBtcTransRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignBtcTransRequest.Merge(m, src)
}
func (m *SignBtcTransRequest) XXX_Size() int {
	return xxx_messageInfo_SignBtcTransRequest.Size(m)
}
func (m *SignBtcTransRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignBtcTransRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignBtcTransRequest proto.InternalMessageInfo

func (m *SignBtcTransRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignBtcTransRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SignBtcTransRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SignBtcTransRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SignBtcTransRequest) GetUnspentlist() []byte {
	if m != nil {
		return m.Unspentlist
	}
	return nil
}

type SignBtcTransResponse struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Signtx               []byte   `protobuf:"bytes,2,opt,name=signtx,proto3" json:"signtx,omitempty"`
	Success              string   `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignBtcTransResponse) Reset()         { *m = SignBtcTransResponse{} }
func (m *SignBtcTransResponse) String() string { return proto.CompactTextString(m) }
func (*SignBtcTransResponse) ProtoMessage()    {}
func (*SignBtcTransResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{8}
}

func (m *SignBtcTransResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignBtcTransResponse.Unmarshal(m, b)
}
func (m *SignBtcTransResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignBtcTransResponse.Marshal(b, m, deterministic)
}
func (m *SignBtcTransResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignBtcTransResponse.Merge(m, src)
}
func (m *SignBtcTransResponse) XXX_Size() int {
	return xxx_messageInfo_SignBtcTransResponse.Size(m)
}
func (m *SignBtcTransResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignBtcTransResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignBtcTransResponse proto.InternalMessageInfo

func (m *SignBtcTransResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignBtcTransResponse) GetSigntx() []byte {
	if m != nil {
		return m.Signtx
	}
	return nil
}

func (m *SignBtcTransResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type SignUsdtTransRequest struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Unspentlist          []byte   `protobuf:"bytes,5,opt,name=unspentlist,proto3" json:"unspentlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUsdtTransRequest) Reset()         { *m = SignUsdtTransRequest{} }
func (m *SignUsdtTransRequest) String() string { return proto.CompactTextString(m) }
func (*SignUsdtTransRequest) ProtoMessage()    {}
func (*SignUsdtTransRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{9}
}

func (m *SignUsdtTransRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUsdtTransRequest.Unmarshal(m, b)
}
func (m *SignUsdtTransRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUsdtTransRequest.Marshal(b, m, deterministic)
}
func (m *SignUsdtTransRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUsdtTransRequest.Merge(m, src)
}
func (m *SignUsdtTransRequest) XXX_Size() int {
	return xxx_messageInfo_SignUsdtTransRequest.Size(m)
}
func (m *SignUsdtTransRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUsdtTransRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUsdtTransRequest proto.InternalMessageInfo

func (m *SignUsdtTransRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignUsdtTransRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SignUsdtTransRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SignUsdtTransRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SignUsdtTransRequest) GetUnspentlist() []byte {
	if m != nil {
		return m.Unspentlist
	}
	return nil
}

type SignUsdtTransResponse struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Signedhash           string   `protobuf:"bytes,2,opt,name=signedhash,proto3" json:"signedhash,omitempty"`
	Success              string   `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUsdtTransResponse) Reset()         { *m = SignUsdtTransResponse{} }
func (m *SignUsdtTransResponse) String() string { return proto.CompactTextString(m) }
func (*SignUsdtTransResponse) ProtoMessage()    {}
func (*SignUsdtTransResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{10}
}

func (m *SignUsdtTransResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUsdtTransResponse.Unmarshal(m, b)
}
func (m *SignUsdtTransResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUsdtTransResponse.Marshal(b, m, deterministic)
}
func (m *SignUsdtTransResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUsdtTransResponse.Merge(m, src)
}
func (m *SignUsdtTransResponse) XXX_Size() int {
	return xxx_messageInfo_SignUsdtTransResponse.Size(m)
}
func (m *SignUsdtTransResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUsdtTransResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUsdtTransResponse proto.InternalMessageInfo

func (m *SignUsdtTransResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *SignUsdtTransResponse) GetSignedhash() string {
	if m != nil {
		return m.Signedhash
	}
	return ""
}

func (m *SignUsdtTransResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type UpdateTransStatusRequest struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Cointype             string   `protobuf:"bytes,2,opt,name=cointype,proto3" json:"cointype,omitempty"`
	Txid                 string   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTransStatusRequest) Reset()         { *m = UpdateTransStatusRequest{} }
func (m *UpdateTransStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTransStatusRequest) ProtoMessage()    {}
func (*UpdateTransStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{11}
}

func (m *UpdateTransStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTransStatusRequest.Unmarshal(m, b)
}
func (m *UpdateTransStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTransStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTransStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTransStatusRequest.Merge(m, src)
}
func (m *UpdateTransStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTransStatusRequest.Size(m)
}
func (m *UpdateTransStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTransStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTransStatusRequest proto.InternalMessageInfo

func (m *UpdateTransStatusRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *UpdateTransStatusRequest) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

func (m *UpdateTransStatusRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *UpdateTransStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateTransStatusResponse struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Cointype             string   `protobuf:"bytes,2,opt,name=cointype,proto3" json:"cointype,omitempty"`
	Txid                 string   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Success              string   `protobuf:"bytes,4,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTransStatusResponse) Reset()         { *m = UpdateTransStatusResponse{} }
func (m *UpdateTransStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTransStatusResponse) ProtoMessage()    {}
func (*UpdateTransStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{12}
}

func (m *UpdateTransStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTransStatusResponse.Unmarshal(m, b)
}
func (m *UpdateTransStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTransStatusResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTransStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTransStatusResponse.Merge(m, src)
}
func (m *UpdateTransStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTransStatusResponse.Size(m)
}
func (m *UpdateTransStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTransStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTransStatusResponse proto.InternalMessageInfo

func (m *UpdateTransStatusResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *UpdateTransStatusResponse) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

func (m *UpdateTransStatusResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *UpdateTransStatusResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

type CollectionRequest struct {
	Cointype             string   `protobuf:"bytes,1,opt,name=cointype,proto3" json:"cointype,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionRequest) Reset()         { *m = CollectionRequest{} }
func (m *CollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CollectionRequest) ProtoMessage()    {}
func (*CollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{13}
}

func (m *CollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionRequest.Unmarshal(m, b)
}
func (m *CollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionRequest.Marshal(b, m, deterministic)
}
func (m *CollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionRequest.Merge(m, src)
}
func (m *CollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CollectionRequest.Size(m)
}
func (m *CollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionRequest proto.InternalMessageInfo

func (m *CollectionRequest) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

func (m *CollectionRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *CollectionRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type CollectionResponse struct {
	Cointype             string   `protobuf:"bytes,1,opt,name=cointype,proto3" json:"cointype,omitempty"`
	Isfinish             string   `protobuf:"bytes,2,opt,name=isfinish,proto3" json:"isfinish,omitempty"`
	Addrlist             []byte   `protobuf:"bytes,3,opt,name=addrlist,proto3" json:"addrlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionResponse) Reset()         { *m = CollectionResponse{} }
func (m *CollectionResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionResponse) ProtoMessage()    {}
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743ac23bcba077a, []int{14}
}

func (m *CollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResponse.Unmarshal(m, b)
}
func (m *CollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResponse.Marshal(b, m, deterministic)
}
func (m *CollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResponse.Merge(m, src)
}
func (m *CollectionResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionResponse.Size(m)
}
func (m *CollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResponse proto.InternalMessageInfo

func (m *CollectionResponse) GetCointype() string {
	if m != nil {
		return m.Cointype
	}
	return ""
}

func (m *CollectionResponse) GetIsfinish() string {
	if m != nil {
		return m.Isfinish
	}
	return ""
}

func (m *CollectionResponse) GetAddrlist() []byte {
	if m != nil {
		return m.Addrlist
	}
	return nil
}

func init() {
	proto.RegisterType((*Unspent)(nil), "proto.Unspent")
	proto.RegisterType((*InsertAddressRequest)(nil), "proto.InsertAddressRequest")
	proto.RegisterType((*InsertAddressResponse)(nil), "proto.InsertAddressResponse")
	proto.RegisterType((*GetHDAddressRequest)(nil), "proto.GetHDAddressRequest")
	proto.RegisterType((*GetHDAddressResponse)(nil), "proto.GetHDAddressResponse")
	proto.RegisterType((*SignEthTransRequest)(nil), "proto.SignEthTransRequest")
	proto.RegisterType((*SignEthTransResponse)(nil), "proto.SignEthTransResponse")
	proto.RegisterType((*SignBtcTransRequest)(nil), "proto.SignBtcTransRequest")
	proto.RegisterType((*SignBtcTransResponse)(nil), "proto.SignBtcTransResponse")
	proto.RegisterType((*SignUsdtTransRequest)(nil), "proto.SignUsdtTransRequest")
	proto.RegisterType((*SignUsdtTransResponse)(nil), "proto.SignUsdtTransResponse")
	proto.RegisterType((*UpdateTransStatusRequest)(nil), "proto.UpdateTransStatusRequest")
	proto.RegisterType((*UpdateTransStatusResponse)(nil), "proto.UpdateTransStatusResponse")
	proto.RegisterType((*CollectionRequest)(nil), "proto.CollectionRequest")
	proto.RegisterType((*CollectionResponse)(nil), "proto.CollectionResponse")
}

func init() { proto.RegisterFile("proto/wallet.proto", fileDescriptor_2743ac23bcba077a) }

var fileDescriptor_2743ac23bcba077a = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0xa6, 0xfb, 0x0b, 0xc7, 0xd5, 0xc8, 0xb0, 0x90, 0x52, 0x8c, 0x6e, 0x7a, 0x45, 0xbc, 0xc0,
	0xa8, 0x4f, 0xa0, 0x68, 0x94, 0xe0, 0x85, 0x29, 0x12, 0xbc, 0x74, 0x68, 0x07, 0x76, 0x62, 0x99,
	0xd6, 0xce, 0x29, 0x3f, 0x26, 0x3e, 0x80, 0xbe, 0x85, 0x89, 0x6f, 0xe7, 0x4b, 0x98, 0xf9, 0x69,
	0x99, 0x2e, 0x85, 0xc5, 0xc4, 0xc4, 0xab, 0x9d, 0x6f, 0xce, 0xf4, 0x9c, 0xf3, 0x7d, 0x67, 0xe6,
	0x5b, 0x20, 0x79, 0x91, 0x61, 0xf6, 0xe4, 0x8c, 0xa6, 0x29, 0xc3, 0x2d, 0x0d, 0x48, 0x5f, 0xff,
	0x84, 0x3f, 0x3d, 0x18, 0xee, 0x0b, 0x99, 0x33, 0x81, 0x84, 0x40, 0x0f, 0xcf, 0x79, 0xe2, 0x7b,
	0x13, 0x6f, 0x73, 0x29, 0xd2, 0x6b, 0xb5, 0x77, 0x9a, 0x95, 0xe8, 0x77, 0x26, 0xde, 0x66, 0x3f,
	0xd2, 0x6b, 0xe2, 0xc3, 0x90, 0x26, 0x49, 0xc1, 0xa4, 0xf4, 0xbb, 0xfa, 0x68, 0x05, 0x75, 0x24,
	0x8e, 0xb3, 0x52, 0xa0, 0xdf, 0xb3, 0x11, 0x03, 0x49, 0x08, 0x23, 0x19, 0x17, 0x3c, 0xc7, 0xf7,
	0xe5, 0xe1, 0x2e, 0xbb, 0xf0, 0xfb, 0x3a, 0xdc, 0xd8, 0x23, 0x6b, 0x30, 0xa0, 0x27, 0xfa, 0xe3,
	0xc1, 0xc4, 0xdb, 0xec, 0x44, 0x16, 0x85, 0x87, 0x30, 0xde, 0x11, 0x92, 0x15, 0xf8, 0xc2, 0x94,
	0x89, 0xd8, 0x97, 0x92, 0x49, 0x24, 0x01, 0x2c, 0xc6, 0x19, 0x17, 0x78, 0x91, 0x33, 0xdb, 0x73,
	0x8d, 0xdd, 0x1e, 0x3b, 0xcd, 0x1e, 0xc7, 0xd0, 0xcf, 0x0b, 0x7e, 0xfa, 0xd9, 0xf6, 0x6e, 0x40,
	0xb8, 0x0b, 0xab, 0x33, 0x35, 0x64, 0x9e, 0x09, 0xd9, 0x48, 0xe4, 0x5d, 0x21, 0x2b, 0xcb, 0x38,
	0x76, 0x4a, 0x58, 0x18, 0x3e, 0x85, 0x95, 0x37, 0x0c, 0xdf, 0xbe, 0xba, 0x7d, 0xbf, 0xe1, 0x63,
	0x18, 0x37, 0x3f, 0xb1, 0xe5, 0x09, 0xf4, 0x54, 0xbd, 0x6a, 0x26, 0x6a, 0x1d, 0xfe, 0xf6, 0x60,
	0x65, 0x8f, 0x1f, 0x8b, 0xd7, 0x38, 0xfd, 0x50, 0x50, 0x51, 0xe7, 0x5f, 0x83, 0x81, 0x64, 0x05,
	0xa7, 0xa9, 0x3d, 0x6d, 0x91, 0xca, 0x71, 0x54, 0x64, 0x27, 0xb6, 0x4b, 0xbd, 0x26, 0xf7, 0xa0,
	0x83, 0x99, 0x95, 0xa0, 0x83, 0x99, 0x52, 0x45, 0x64, 0x22, 0x66, 0x76, 0x6e, 0x06, 0xa8, 0xdd,
	0x53, 0x9a, 0x96, 0xcc, 0x8e, 0xcb, 0x00, 0xc5, 0xe3, 0x98, 0xca, 0x94, 0x9f, 0x70, 0x33, 0xa9,
	0xa5, 0xa8, 0xc6, 0x36, 0x96, 0x17, 0x3c, 0x66, 0xfe, 0xb0, 0x8e, 0x69, 0xac, 0x04, 0x8b, 0xa7,
	0x94, 0x0b, 0x9e, 0xf8, 0x8b, 0x46, 0x30, 0x0b, 0x8d, 0x32, 0x02, 0x0b, 0x1a, 0xa3, 0xbf, 0x54,
	0x29, 0x63, 0xb0, 0x9a, 0x7e, 0x93, 0xac, 0x55, 0xe6, 0x3a, 0xb6, 0x3e, 0x0c, 0x0b, 0x7a, 0x36,
	0xa5, 0x72, 0x5a, 0x8d, 0xc5, 0x42, 0x77, 0x60, 0xdd, 0xe6, 0xc0, 0xbe, 0x5b, 0x45, 0x5f, 0x62,
	0xfc, 0x2f, 0x15, 0x35, 0xda, 0xf5, 0x5c, 0xed, 0x26, 0x70, 0xa7, 0x34, 0xcf, 0x2d, 0xe5, 0x12,
	0xb5, 0xae, 0xa3, 0xc8, 0xdd, 0x0a, 0x3f, 0x19, 0xbe, 0x97, 0xad, 0xcc, 0xe1, 0xab, 0xf6, 0xf9,
	0xb1, 0xc0, 0x73, 0xdd, 0xcd, 0x28, 0xb2, 0xe8, 0x06, 0xb6, 0x3f, 0x3c, 0x53, 0x62, 0x5f, 0x26,
	0xf8, 0xdf, 0xe9, 0x72, 0x58, 0x9d, 0xe9, 0x65, 0x0e, 0xdf, 0x87, 0x00, 0x8a, 0x21, 0x4b, 0x9c,
	0x11, 0x3b, 0x3b, 0x37, 0xf0, 0xfe, 0x0a, 0xfe, 0x7e, 0x9e, 0x50, 0x64, 0xba, 0xd0, 0x1e, 0x52,
	0x2c, 0xe7, 0x52, 0x77, 0xdf, 0x6c, 0x67, 0xc6, 0x63, 0x2a, 0xbf, 0xec, 0x3a, 0x7e, 0xa9, 0xf2,
	0xe8, 0xc4, 0x56, 0x07, 0x8b, 0xc2, 0x6f, 0xb0, 0xde, 0x52, 0x7b, 0x0e, 0xd5, 0xbf, 0x2d, 0xee,
	0x50, 0xef, 0x35, 0xa9, 0x1f, 0xc0, 0xf2, 0x76, 0x96, 0xa6, 0x2c, 0x46, 0x9e, 0x89, 0xdb, 0xf8,
	0xe7, 0x18, 0xfa, 0x12, 0x69, 0x81, 0xb6, 0xae, 0x01, 0xe4, 0x3e, 0x74, 0x99, 0xa8, 0x6a, 0xaa,
	0x65, 0x38, 0x05, 0xe2, 0x26, 0xb6, 0x84, 0x6e, 0xca, 0x1c, 0xc0, 0x22, 0x97, 0x47, 0x5c, 0xf0,
	0x7a, 0x7a, 0x35, 0x56, 0x31, 0xe5, 0x70, 0xfa, 0xae, 0x74, 0xf5, 0x5d, 0xa9, 0xf1, 0xb3, 0x5f,
	0x3d, 0x18, 0x1c, 0xe8, 0x7f, 0x30, 0xf2, 0x0e, 0xee, 0x36, 0xcc, 0x9a, 0x6c, 0x98, 0x3f, 0xb5,
	0xad, 0xb6, 0xbf, 0x89, 0xe0, 0x41, 0x7b, 0xd0, 0xb4, 0x1a, 0x2e, 0x90, 0x1d, 0x18, 0xb9, 0xd6,
	0x4b, 0x02, 0x7b, 0xbe, 0xc5, 0xc2, 0x83, 0x8d, 0xd6, 0x98, 0x9b, 0xca, 0xf5, 0xaa, 0x3a, 0x55,
	0x8b, 0x5b, 0xd7, 0xa9, 0xda, 0xcc, 0xed, 0x32, 0x55, 0x65, 0x03, 0x8d, 0x54, 0x33, 0x36, 0xd5,
	0x48, 0x35, 0xeb, 0x1b, 0xe1, 0x82, 0x92, 0xab, 0xf1, 0xc4, 0x88, 0x7b, 0x7e, 0xd6, 0x04, 0x6a,
	0xb9, 0x5a, 0x5f, 0x65, 0xb8, 0x40, 0x3e, 0xc2, 0xf2, 0x95, 0x9b, 0x4c, 0x1e, 0xd9, 0x8f, 0xae,
	0x7b, 0x5f, 0xc1, 0xe4, 0xfa, 0x03, 0x75, 0xe6, 0x6d, 0x80, 0xcb, 0xbb, 0x44, 0x7c, 0xfb, 0xc5,
	0x95, 0x7b, 0x1b, 0xac, 0xb7, 0x44, 0xaa, 0x24, 0x87, 0x03, 0x1d, 0x7b, 0xfe, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0xbc, 0xbf, 0x34, 0xf4, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	InsertAddress(ctx context.Context, in *InsertAddressRequest, opts ...grpc.CallOption) (*InsertAddressResponse, error)
	GetHDAddress(ctx context.Context, in *GetHDAddressRequest, opts ...grpc.CallOption) (*GetHDAddressResponse, error)
	SignEthTrans(ctx context.Context, in *SignEthTransRequest, opts ...grpc.CallOption) (*SignEthTransResponse, error)
	SignBtcTrans(ctx context.Context, in *SignBtcTransRequest, opts ...grpc.CallOption) (*SignBtcTransResponse, error)
	SignUsdtTrans(ctx context.Context, in *SignUsdtTransRequest, opts ...grpc.CallOption) (*SignUsdtTransResponse, error)
	UpdateTransStatus(ctx context.Context, in *UpdateTransStatusRequest, opts ...grpc.CallOption) (*UpdateTransStatusResponse, error)
	Collection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*CollectionResponse, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) InsertAddress(ctx context.Context, in *InsertAddressRequest, opts ...grpc.CallOption) (*InsertAddressResponse, error) {
	out := new(InsertAddressResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/InsertAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetHDAddress(ctx context.Context, in *GetHDAddressRequest, opts ...grpc.CallOption) (*GetHDAddressResponse, error) {
	out := new(GetHDAddressResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/GetHDAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SignEthTrans(ctx context.Context, in *SignEthTransRequest, opts ...grpc.CallOption) (*SignEthTransResponse, error) {
	out := new(SignEthTransResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/SignEthTrans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SignBtcTrans(ctx context.Context, in *SignBtcTransRequest, opts ...grpc.CallOption) (*SignBtcTransResponse, error) {
	out := new(SignBtcTransResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/SignBtcTrans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SignUsdtTrans(ctx context.Context, in *SignUsdtTransRequest, opts ...grpc.CallOption) (*SignUsdtTransResponse, error) {
	out := new(SignUsdtTransResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/SignUsdtTrans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) UpdateTransStatus(ctx context.Context, in *UpdateTransStatusRequest, opts ...grpc.CallOption) (*UpdateTransStatusResponse, error) {
	out := new(UpdateTransStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/UpdateTransStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Collection(ctx context.Context, in *CollectionRequest, opts ...grpc.CallOption) (*CollectionResponse, error) {
	out := new(CollectionResponse)
	err := c.cc.Invoke(ctx, "/proto.Wallet/Collection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	InsertAddress(context.Context, *InsertAddressRequest) (*InsertAddressResponse, error)
	GetHDAddress(context.Context, *GetHDAddressRequest) (*GetHDAddressResponse, error)
	SignEthTrans(context.Context, *SignEthTransRequest) (*SignEthTransResponse, error)
	SignBtcTrans(context.Context, *SignBtcTransRequest) (*SignBtcTransResponse, error)
	SignUsdtTrans(context.Context, *SignUsdtTransRequest) (*SignUsdtTransResponse, error)
	UpdateTransStatus(context.Context, *UpdateTransStatusRequest) (*UpdateTransStatusResponse, error)
	Collection(context.Context, *CollectionRequest) (*CollectionResponse, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_InsertAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).InsertAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/InsertAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).InsertAddress(ctx, req.(*InsertAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetHDAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHDAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetHDAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/GetHDAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetHDAddress(ctx, req.(*GetHDAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SignEthTrans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignEthTransRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SignEthTrans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/SignEthTrans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SignEthTrans(ctx, req.(*SignEthTransRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SignBtcTrans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBtcTransRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SignBtcTrans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/SignBtcTrans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SignBtcTrans(ctx, req.(*SignBtcTransRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SignUsdtTrans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUsdtTransRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SignUsdtTrans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/SignUsdtTrans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SignUsdtTrans(ctx, req.(*SignUsdtTransRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_UpdateTransStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).UpdateTransStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/UpdateTransStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).UpdateTransStatus(ctx, req.(*UpdateTransStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Collection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Collection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Wallet/Collection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Collection(ctx, req.(*CollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertAddress",
			Handler:    _Wallet_InsertAddress_Handler,
		},
		{
			MethodName: "GetHDAddress",
			Handler:    _Wallet_GetHDAddress_Handler,
		},
		{
			MethodName: "SignEthTrans",
			Handler:    _Wallet_SignEthTrans_Handler,
		},
		{
			MethodName: "SignBtcTrans",
			Handler:    _Wallet_SignBtcTrans_Handler,
		},
		{
			MethodName: "SignUsdtTrans",
			Handler:    _Wallet_SignUsdtTrans_Handler,
		},
		{
			MethodName: "UpdateTransStatus",
			Handler:    _Wallet_UpdateTransStatus_Handler,
		},
		{
			MethodName: "Collection",
			Handler:    _Wallet_Collection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wallet.proto",
}
